-- 2022년 1월의 카테고리 별 도서 판매량을 합산하고, 카테고리(CATEGORY), 총 판매량(TOTAL_SALES) 리스트를 출력하는 SQL문을 작성해주세요. 결과는 카테고리명을 기준으로 오름차순 정렬해주세요.
-- Oracle
-- GROUP BY

SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B
    INNER JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(S.SALES_DATE,'YYYY-MM-DD') LIKE '2022-01%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC
;