-- CAR_RENTAL_COMPANY_CAR 테이블과 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 자동차 종류가 '트럭'인 자동차의 대여 기록에 대해서 대여 기록 별로 대여 금액(컬럼명: FEE)을 구하여 대여 기록 ID와 대여 금액 리스트를 출력하는 SQL문을 작성해주세요. 결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 대여 기록 ID를 기준으로 내림차순 정렬해주세요.
-- Oracle
-- String, Date

SELECT HISTORY_ID, MIN(DAILY_FEE * (1 - NVL(DISCOUNT_RATE, 0) / 100) * (END_DATE - START_DATE + 1)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    LEFT JOIN CAR_RENTAL_COMPANY_CAR c
    ON h.CAR_ID = c.CAR_ID
    LEFT JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN) p
    ON (c.CAR_TYPE = p.CAR_TYPE AND (END_DATE - START_DATE + 1) >= REGEXP_REPLACE(DURATION_TYPE, '[^0-9]+'))
WHERE c.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC
;