-- 2022년 1월의 도서 판매 데이터를 기준으로 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력하는 SQL문을 작성해주세요. 결과는 저자 ID를 오름차순으로, 저자 ID가 같다면 카테고리를 내림차순 정렬해주세요.
-- Oracle
-- GROUP BY

SELECT T.AUTHOR_ID, T.AUTHOR_NAME, T.CATEGORY, SUM(T.TOTAL_SALES) AS TOTAL_SALES
FROM
    (
        SELECT B.AUTHOR_ID, A.AUTHOR_NAME, BS.BOOK_ID, BS.SALES_DATE, B.CATEGORY, (BS.SALES * B.PRICE) AS TOTAL_SALES
        FROM BOOK_SALES BS, BOOK B, AUTHOR A
        WHERE B.BOOK_ID = BS.BOOK_ID
          AND B.AUTHOR_ID = A.AUTHOR_ID
          AND BS.SALES_DATE BETWEEN TO_DATE('20220101','YYYY-MM-DD') AND TO_DATE('20220131','YYYY-MM-DD')
    ) T
GROUP BY T.AUTHOR_ID, T.AUTHOR_NAME, T.CATEGORY
ORDER BY 1 ASC, 3 DESC
;